spring.application.name=project-final-course

# ==========================================
# Configuracion de base de datos PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/mantenimiento_db
spring.datasource.username=postgres
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# Configuracion de JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# Configuracion de JWT
# Expiracion en milisegundos: 86400000 = 24 horas
# ==========================================
jwt.secret=c2VndXJpZGFkX3Rva2VuX3NlY3JldG9fc3VwZXJfc2VndXJvX21vZHVsb181XzI2Yml0cw==
jwt.expiration=86400000
